const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const portalLabels={'project-work':'Undergraduate Project Work','field-experience':'Field Experience and Teaching Practice','dissertation':'Dissertation','assessor':'Assessment/Vetting Reports','payroll':'Payroll Portal','auditor':"Auditor's Portal"};
const deptLabels={'education':'Education','business':'Business','arts-social-sciences':'Arts & Social Sciences','science-mathematics':'Science & Mathematics'};
const roleLabels={viewer:'Viewer',officer:'Officer',administrator:'Administrator'};
const fmt=d=>d?new Date(d).toLocaleString():'Built-in';
function size(n){n=Number(n||0);if(!n)return '';if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`;}
async function getJson(url,opt){const r=await fetch(url,opt),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed.');return d;}

// v27: developer/system-admin sections are tabbed to reduce page clutter.
const devTabs=[...document.querySelectorAll('.developer-tab')],devPanels=[...document.querySelectorAll('.developer-panel')];
function activateDeveloperTab(tab){const valid=devTabs.map(b=>b.dataset.devTab);if(!valid.includes(tab))tab='resources';devTabs.forEach(b=>b.classList.toggle('active',b.dataset.devTab===tab));devPanels.forEach(p=>p.classList.toggle('hidden',p.dataset.devPanel!==tab));history.replaceState(null,'',`${location.pathname}${location.search}#${tab}`);}
devTabs.forEach(b=>b.addEventListener('click',()=>activateDeveloperTab(b.dataset.devTab)));

let previewOptions={departments:[],profiles:[],accounts:[]};
function previewSectionsText(sections){return (sections||[]).map(x=>portalLabels[x]||x).join(', ')||'No sections';}
function updatePreviewAccountOptions(){
  const department=document.getElementById('previewDepartment')?.value||'';
  const select=document.getElementById('previewAccount');if(!select)return;
  const list=(previewOptions.accounts||[]).filter(a=>a.active!==false&&(a.departments||[]).includes(department));
  select.innerHTML='<option value="">Select an administrator</option>'+list.map(a=>`<option value="${esc(a.id)}">${esc(a.name||a.username)} · ${esc(roleLabels[a.role]||a.role)} · ${esc(previewSectionsText(a.sections))}</option>`).join('');
}
function updatePreviewProfileHelp(){
  const id=document.getElementById('previewProfile')?.value||'';
  const p=(previewOptions.profiles||[]).find(x=>x.id===id);
  const help=document.getElementById('previewProfileHelp');if(help)help.textContent=p?`${roleLabels[p.role]||p.role}: ${previewSectionsText(p.sections)}.`:'';
}
function updatePreviewMode(){
  const mode=document.getElementById('previewMode')?.value||'profile';
  document.getElementById('previewProfileBlock')?.classList.toggle('hidden',mode!=='profile');
  document.getElementById('previewAccountBlock')?.classList.toggle('hidden',mode!=='account');
}
async function loadPreviewOptions(){
  previewOptions=await getJson('/api/developer/preview-options');
  const department=document.getElementById('previewDepartment'),operationsDepartment=document.getElementById('operationsDepartment'),profile=document.getElementById('previewProfile');
  if(department){department.innerHTML=(previewOptions.departments||[]).map(d=>`<option value="${esc(d.slug)}">${esc(d.name)}</option>`).join('');}
  if(operationsDepartment){operationsDepartment.innerHTML=(previewOptions.departments||[]).map(d=>`<option value="${esc(d.slug)}" ${d.slug==='education'?'selected':''}>${esc(d.name)}</option>`).join('');}
  if(profile){profile.innerHTML=(previewOptions.profiles||[]).map(p=>`<option value="${esc(p.id)}">${esc(p.label)} · ${esc(roleLabels[p.role]||p.role)}</option>`).join('');}
  updatePreviewAccountOptions();updatePreviewProfileHelp();updatePreviewMode();
}

async function launchOperationsPortal(destination){
  const department=document.getElementById('operationsDepartment')?.value||'education',status=document.getElementById('operationsLaunchStatus');
  const button=document.getElementById(destination==='payroll'?'openPayrollPortal':'openAuditorPortal');
  const target=window.open('about:blank','_blank');button.disabled=true;status.className='status';status.textContent=`Opening ${destination==='payroll'?'Payroll':"Auditor's"} Portal…`;
  try{
    const data=await getJson('/api/developer/preview-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'profile',department,destination,profileId:'operations-officer'})});
    status.className='status ok';status.textContent=`${destination==='payroll'?'Payroll':"Auditor's"} Portal opened with access to all departments.`;
    if(target)target.location.href=data.redirect;else location.href=data.redirect;
  }catch(error){if(target)target.close();status.className='status bad';status.textContent=error.message;}finally{button.disabled=false;}
}
document.getElementById('openPayrollPortal')?.addEventListener('click',()=>launchOperationsPortal('payroll'));
document.getElementById('openAuditorPortal')?.addEventListener('click',()=>launchOperationsPortal('auditor'));

async function loadResources(){const data=await getJson('/api/developer/resources');document.getElementById('resourceCount').textContent=data.length;document.getElementById('resourceRows').innerHTML=data.map((r,i)=>`<tr><td>${i+1}</td><td><span class="resource-title">${esc(r.title)}${r.builtIn?'<span class="builtin">BUILT-IN</span>':''}</span>${r.description?`<span class="resource-desc">${esc(r.description)}</span>`:''}</td><td>${esc(r.originalName)}${r.size?`<br><small>${esc(size(r.size))}</small>`:''}</td><td>${(r.departments||[]).length?(r.departments||[]).map(d=>`<span class="tag">${esc(deptLabels[d]||d)}</span>`).join(''):'<span class="tag">All departments</span>'}</td><td>${(r.portals||[]).map(p=>`<span class="tag">${esc(portalLabels[p]||p)}</span>`).join('')}</td><td>${esc(fmt(r.uploadedAt))}</td><td><a class="download" href="${esc(r.downloadUrl)}">Download</a>${r.canDelete?` <button class="danger" onclick="removeResource('${esc(r.id)}')">Delete</button>`:''}</td></tr>`).join('');}
function accountState(a){if(!a.active)return {label:'Disabled',cls:'inactive-pill',detail:''};if(a.passwordSet)return {label:'Ready',cls:'active-pill',detail:a.passwordSetAt?`Password set ${fmt(a.passwordSetAt)}`:''};if(a.invitationEmailStatus==='failed')return {label:'Email failed',cls:'failed-pill',detail:a.invitationLastError||''};if(a.invitationExpired)return {label:'Invite expired',cls:'expired-pill',detail:a.invitationExpiresAt?`Expired ${fmt(a.invitationExpiresAt)}`:''};if(a.invitationEmailStatus==='sent')return {label:'Awaiting setup',cls:'pending-pill',detail:a.invitationExpiresAt?`Expires ${fmt(a.invitationExpiresAt)}`:''};return {label:'Invitation pending',cls:'pending-pill',detail:''};}
async function loadAdmins(){const data=await getJson('/api/developer/admin-users');previewOptions.accounts=data;document.getElementById('adminCount').textContent=data.length;document.getElementById('adminRows').innerHTML=data.map((a,i)=>{const state=accountState(a),inviteLabel=a.passwordSet?'Send Password Reset':'Resend Invite',inviteButton=a.email?`<button class="secondary compact" onclick="sendAdminInvite('${esc(a.id)}')">${inviteLabel}</button>`:'',previewButton=a.active?`<button class="download compact" onclick="previewAdminAccount('${esc(a.id)}')">Preview</button>`:'';return `<tr><td>${i+1}</td><td><strong>${esc(a.name)}</strong><br><small>${esc(a.email||'')}</small><br><small>Username: ${esc(a.username)}</small></td><td><span class="role role-${esc(a.role)}">${esc(roleLabels[a.role]||a.role)}</span></td><td>${(a.departments||[]).map(x=>`<span class="tag">${esc(deptLabels[x]||x)}</span>`).join('')}</td><td>${(a.sections||[]).map(x=>`<span class="tag">${esc(portalLabels[x]||x)}</span>`).join('')}</td><td><span class="${state.cls}">${esc(state.label)}</span>${state.detail?`<span class="status-detail">${esc(state.detail)}</span>`:''}</td><td><div class="button-row">${previewButton}${inviteButton}<button class="secondary compact" onclick="toggleAdmin('${esc(a.id)}',${a.active?'false':'true'})">${a.active?'Disable':'Enable'}</button><button class="danger compact" onclick="deleteAdmin('${esc(a.id)}')">Delete</button></div></td></tr>`;}).join('');}
async function loadCentres(){const data=await getJson('/api/developer/study-centres'),catalogue=data.departments||{},states=data.centreStates||{};document.getElementById('centreCount').textContent=data.total??Object.values(catalogue).reduce((n,list)=>n+(Array.isArray(list)?list.length:0),0);document.getElementById('centreTags').innerHTML=Object.keys(deptLabels).map(slug=>{const list=(Array.isArray(catalogue[slug])?catalogue[slug]:[]).slice().sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true,sensitivity:'base'}));return `<section class="centre-group"><h4>${esc(deptLabels[slug])} <span>${list.length}</span></h4>${list.length?`<div class="centre-item-list">${list.map(c=>{const enabled=states[String(c).toLowerCase()]!==false;return `<span class="centre-tag ${enabled?'':'centre-disabled'}"><span>${esc(c)}</span>${enabled?'':'<small>Disabled</small>'}</span>`}).join('')}</div>`:'<div class="centre-empty">No centres assigned to this department.</div>'}</section>`}).join('');}
async function loadCentreDirectory(){const data=await getJson('/api/developer/study-centre-directory'),list=data.centres||[];document.getElementById('directoryCount').textContent=data.count??list.length;document.getElementById('centreDirectoryRows').innerHTML=list.map((c,i)=>`<tr class="${c.enabled===false?'centre-disabled-row':''}"><td>${i+1}</td><td>${esc(c.id||'')}</td><td><strong>${esc(c.code)}</strong></td><td>${esc(c.name)}</td><td>${(c.departments||[]).map(slug=>`<span class="tag">${esc(deptLabels[slug]||slug)}</span>`).join('')||'<span class="tag">Unassigned</span>'}</td><td><span class="${c.enabled===false?'inactive-pill':'active-pill'}">${c.enabled===false?'Disabled':'Enabled'}</span></td><td><button class="secondary compact" type="button" onclick="toggleCentreStatus('${encodeURIComponent(c.code)}',${c.enabled===false?'true':'false'})">${c.enabled===false?'Enable':'Disable'}</button></td></tr>`).join('')||'<tr><td colspan="7">No centre codes are configured.</td></tr>';}
async function loadPortalSettings(){const d=await getJson('/api/developer/portal-settings');document.getElementById('fieldExperienceClaimRequirement').value=d.fieldExperienceClaimFormRequired?'required':'optional';}
async function loadAll(){await Promise.all([loadResources(),loadAdmins(),loadCentres(),loadCentreDirectory(),loadPortalSettings(),loadPreviewOptions()]);}

const previewForm=document.getElementById('previewForm'),previewStatus=document.getElementById('previewStatus'),launchPreviewBtn=document.getElementById('launchPreviewBtn');
document.getElementById('previewDepartment')?.addEventListener('change',updatePreviewAccountOptions);
document.getElementById('previewMode')?.addEventListener('change',updatePreviewMode);
document.getElementById('previewProfile')?.addEventListener('change',updatePreviewProfileHelp);
previewForm?.addEventListener('submit',async e=>{
  e.preventDefault();
  const mode=document.getElementById('previewMode').value,department=document.getElementById('previewDepartment').value,destination=document.getElementById('previewDestination').value;
  const payload={mode,department,destination};
  if(mode==='account'){payload.accountId=document.getElementById('previewAccount').value;if(!payload.accountId){previewStatus.className='status bad';previewStatus.textContent='Select an existing administrator account.';return;}}
  else payload.profileId=document.getElementById('previewProfile').value;
  const previewWindow=window.open('about:blank','_blank');
  launchPreviewBtn.disabled=true;previewStatus.className='status';previewStatus.textContent='Creating secure developer preview session…';
  try{
    const d=await getJson('/api/developer/preview-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
    previewStatus.className='status ok';previewStatus.textContent=`Preview ready as ${d.previewLabel}. Opening portal…`;
    if(previewWindow)previewWindow.location.href=d.redirect;else location.href=d.redirect;
  }catch(err){if(previewWindow)previewWindow.close();previewStatus.className='status bad';previewStatus.textContent=err.message;}finally{launchPreviewBtn.disabled=false;}
});

const resourceForm=document.getElementById('resourceForm'),resourceStatus=document.getElementById('resourceStatus'),uploadBtn=document.getElementById('uploadBtn');
resourceForm.addEventListener('submit',async e=>{e.preventDefault();if(!resourceForm.querySelector('input[name="departments"]:checked')){resourceStatus.className='status bad';resourceStatus.textContent='Select at least one department.';return;}if(!resourceForm.querySelector('input[name="portals"]:checked')){resourceStatus.className='status bad';resourceStatus.textContent='Select at least one portal.';return;}uploadBtn.disabled=true;try{await getJson('/api/developer/resources',{method:'POST',body:new FormData(resourceForm)});resourceForm.reset();resourceStatus.className='status ok';resourceStatus.textContent='Resource published.';await loadResources();}catch(e){resourceStatus.className='status bad';resourceStatus.textContent=e.message;}finally{uploadBtn.disabled=false;}});
window.removeResource=async id=>{if(!confirm('Delete this resource?'))return;try{await getJson(`/api/developer/resources/${encodeURIComponent(id)}`,{method:'DELETE'});await loadResources();}catch(e){alert(e.message);}};

const adminForm=document.getElementById('adminForm'),adminStatus=document.getElementById('adminStatus'),createAdminBtn=document.getElementById('createAdminBtn');
adminForm.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(adminForm),payload={name:fd.get('name'),email:fd.get('email'),username:fd.get('username'),role:fd.get('role'),departments:fd.getAll('departments'),sections:fd.getAll('sections')};if(!payload.departments.length||!payload.sections.length){adminStatus.className='status bad';adminStatus.textContent='Select at least one department and one submission section.';return;}createAdminBtn.disabled=true;try{const d=await getJson('/api/developer/admin-users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});adminForm.reset();adminStatus.className=d.emailSent?'status ok':'status warn';adminStatus.textContent=d.emailSent?'Administrator account created and a one-time password setup link was emailed.':(d.warning||'Administrator account created, but the invitation email was not sent.');await loadAdmins();}catch(e){adminStatus.className='status bad';adminStatus.textContent=e.message;}finally{createAdminBtn.disabled=false;}});
window.sendAdminInvite=async id=>{if(!confirm('Send a new one-time password setup link to this administrator? Any earlier setup link will stop working.'))return;try{await getJson(`/api/developer/admin-users/${id}/resend-invitation`,{method:'POST'});adminStatus.className='status ok';adminStatus.textContent='A new one-time password setup link was emailed.';await loadAdmins();}catch(e){adminStatus.className='status bad';adminStatus.textContent=e.message;await loadAdmins().catch(()=>{});}};
window.deleteAdmin=async id=>{if(!confirm('Delete this administrator account?'))return;try{await getJson(`/api/developer/admin-users/${id}`,{method:'DELETE'});await loadAdmins();}catch(e){alert(e.message);}};
window.toggleAdmin=async(id,active)=>{try{await getJson(`/api/developer/admin-users/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({active})});await loadAdmins();}catch(e){alert(e.message);}};
window.previewAdminAccount=id=>{const account=(previewOptions.accounts||[]).find(a=>a.id===id);if(!account)return alert('Refresh the page and try again.');activateDeveloperTab('preview');document.getElementById('previewMode').value='account';updatePreviewMode();const department=(account.departments||[])[0]||'';if(department)document.getElementById('previewDepartment').value=department;updatePreviewAccountOptions();document.getElementById('previewAccount').value=id;const sections=account.sections||[];document.getElementById('previewDestination').value=sections.some(x=>['project-work','field-experience','dissertation','assessor'].includes(x))?'admin':sections.includes('payroll')?'payroll':sections.includes('auditor')?'auditor':'admin';document.getElementById('previewStatus').className='status';document.getElementById('previewStatus').textContent=`Ready to preview ${account.name||account.username} without their password.`;};

const singleCentreForm=document.getElementById('singleCentreForm'),singleCentreStatus=document.getElementById('singleCentreStatus'),addSingleCentreBtn=document.getElementById('addSingleCentreBtn');
singleCentreForm.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(singleCentreForm),payload={id:fd.get('id'),code:fd.get('code'),name:fd.get('name'),departments:fd.getAll('departments')};if(!payload.departments.length){singleCentreStatus.className='status bad';singleCentreStatus.textContent='Select at least one department.';return;}addSingleCentreBtn.disabled=true;try{const d=await getJson('/api/developer/study-centres/item',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});singleCentreForm.reset();singleCentreStatus.className='status ok';singleCentreStatus.textContent=`${d.name} saved, enabled and assigned without replacing existing lists.`;await Promise.all([loadCentres(),loadCentreDirectory()]);}catch(e){singleCentreStatus.className='status bad';singleCentreStatus.textContent=e.message;}finally{addSingleCentreBtn.disabled=false;}});

const centreForm=document.getElementById('centreForm'),centreStatus=document.getElementById('centreStatus'),uploadCentresBtn=document.getElementById('uploadCentresBtn');
centreForm.addEventListener('submit',async e=>{e.preventDefault();if(!centreForm.querySelector('input[name="departments"]:checked')){centreStatus.className='status bad';centreStatus.textContent='Select at least one department for this centre list.';return;}if(!confirm('Replace the complete centre list for the selected department(s) with this CSV?'))return;uploadCentresBtn.disabled=true;try{const d=await getJson('/api/developer/study-centres',{method:'POST',body:new FormData(centreForm)});centreForm.reset();centreStatus.className='status ok';centreStatus.textContent=`Published ${d.count} study centres for ${d.departments.length} department${d.departments.length===1?'':'s'}.`;await loadCentres();}catch(e){centreStatus.className='status bad';centreStatus.textContent=e.message;}finally{uploadCentresBtn.disabled=false;}});
document.getElementById('resetCentres').onclick=async()=>{if(!confirm('Restore the approved study-centre list for all four departments? Disabled status in the code directory is unchanged.'))return;try{const d=await getJson('/api/developer/study-centres/reset',{method:'POST'});centreStatus.className='status ok';centreStatus.textContent=`Restored ${d.count} approved centres to all departments.`;await loadCentres();}catch(e){centreStatus.className='status bad';centreStatus.textContent=e.message;}};

const singleCentreDirectoryForm=document.getElementById('singleCentreDirectoryForm'),singleCentreDirectoryStatus=document.getElementById('singleCentreDirectoryStatus'),saveSingleCentreDirectoryBtn=document.getElementById('saveSingleCentreDirectoryBtn');
singleCentreDirectoryForm.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(singleCentreDirectoryForm),payload={id:fd.get('id'),code:fd.get('code'),name:fd.get('name'),departments:fd.getAll('departments')};saveSingleCentreDirectoryBtn.disabled=true;try{const d=await getJson('/api/developer/study-centre-directory/item',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});singleCentreDirectoryForm.reset();singleCentreDirectoryStatus.className='status ok';singleCentreDirectoryStatus.textContent=d.updated?'Centre record updated.':'Centre record added.';await Promise.all([loadCentreDirectory(),loadCentres()]);}catch(e){singleCentreDirectoryStatus.className='status bad';singleCentreDirectoryStatus.textContent=e.message;}finally{saveSingleCentreDirectoryBtn.disabled=false;}});
window.toggleCentreStatus=async(encodedCode,enabled)=>{const code=decodeURIComponent(encodedCode);if(!confirm(`${enabled?'Enable':'Disable'} centre ${code}? ${enabled?'It will return to its assigned public department lists.':'It will be hidden from public department lists without deleting its record, code or assignments.'}`))return;try{const d=await getJson(`/api/developer/study-centre-directory/${encodeURIComponent(code)}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})});singleCentreDirectoryStatus.className='status ok';singleCentreDirectoryStatus.textContent=d.message;await Promise.all([loadCentreDirectory(),loadCentres()]);}catch(e){singleCentreDirectoryStatus.className='status bad';singleCentreDirectoryStatus.textContent=e.message;}};

const centreDirectoryForm=document.getElementById('centreDirectoryForm'),centreDirectoryStatus=document.getElementById('centreDirectoryStatus'),uploadCentreDirectoryBtn=document.getElementById('uploadCentreDirectoryBtn');
centreDirectoryForm.addEventListener('submit',async e=>{e.preventDefault();if(!centreDirectoryForm.querySelector('input[name="departments"]:checked')){centreDirectoryStatus.className='status bad';centreDirectoryStatus.textContent='Select at least one department for the imported centres.';return;}if(!confirm('Replace the current study-centre code directory and publish all imported centres to the selected departments?'))return;uploadCentreDirectoryBtn.disabled=true;try{const d=await getJson('/api/developer/study-centre-directory',{method:'POST',body:new FormData(centreDirectoryForm)});centreDirectoryForm.reset();centreDirectoryStatus.className='status ok';centreDirectoryStatus.textContent=`Updated ${d.count} centre-code records and ${d.departments.length} department list${d.departments.length===1?'':'s'}.`;await Promise.all([loadCentreDirectory(),loadCentres()]);}catch(e){centreDirectoryStatus.className='status bad';centreDirectoryStatus.textContent=e.message;}finally{uploadCentreDirectoryBtn.disabled=false;}});
document.getElementById('resetCentreDirectory').onclick=async()=>{if(!confirm('Restore the approved study-centre code directory and republish its centres to all four departments?'))return;try{const d=await getJson('/api/developer/study-centre-directory/reset',{method:'POST'});centreDirectoryStatus.className='status ok';centreDirectoryStatus.textContent=`Restored ${d.count} approved centre-code records and all department lists.`;await Promise.all([loadCentreDirectory(),loadCentres()]);}catch(e){centreDirectoryStatus.className='status bad';centreDirectoryStatus.textContent=e.message;}};

const portalSettingsForm=document.getElementById('portalSettingsForm'),portalSettingsStatus=document.getElementById('portalSettingsStatus'),savePortalSettingsBtn=document.getElementById('savePortalSettingsBtn');
portalSettingsForm.addEventListener('submit',async e=>{e.preventDefault();savePortalSettingsBtn.disabled=true;try{const required=document.getElementById('fieldExperienceClaimRequirement').value==='required';const d=await getJson('/api/developer/portal-settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({fieldExperienceClaimFormRequired:required})});portalSettingsStatus.className='status ok';portalSettingsStatus.textContent=`Field Experience and Teaching Practice Claim Form is now ${d.fieldExperienceClaimFormRequired?'Compulsory':'Optional'}.`;}catch(e){portalSettingsStatus.className='status bad';portalSettingsStatus.textContent=e.message;}finally{savePortalSettingsBtn.disabled=false;}});

document.getElementById('refreshResources').onclick=()=>loadResources().catch(e=>alert(e.message));
document.getElementById('refreshAdmins').onclick=()=>loadAdmins().catch(e=>alert(e.message));
loadAll().then(()=>activateDeveloperTab((location.hash||'').replace('#','')||'resources')).catch(e=>{console.error(e);resourceStatus.className='status bad';resourceStatus.textContent=e.message||'Could not load developer data.';});
